esphome:
  name: nodemcu-ac

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "lhXgwnyYrEhWucbALFt2Gj16hR6tQVARZXinpHCw6WQ="

ota:
  password: "3b5494a2a8f9b17f94d5cc9e4142e466"

wifi:
  manual_ip:
    static_ip: 172.16.1.199
    gateway: 172.16.1.1
    subnet: 255.255.255.0  
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nodemcu-Ac Fallback Hotspot"
    password: "DrBAcKshjDMn"

captive_portal:

# status_led:
#  pin: GPIO4
 
# remote_receiver:
#  id: rcvr
#  pin:
#    number: GPIO5
#    inverted: True
#  dump: all
  # - rc_switch
 # Settings to optimize recognition of RF devices
 #tolerance: 50%
 #filter: 250us
 #idle: 4ms
 #buffer_size: 2kb


remote_transmitter:
 pin: GPIO14
 carrier_duty_percent: 50%
climate:
 - platform: climate_ir_lg
   name: "AC"
   header_high: 3265us
   header_low: 9856us 


binary_sensor:
  - platform: gpio
    name: "AC Power"
    internal: true
    pin: 
       number: GPIO5
       mode:
         input: True
         pullup: true
    on_press:
      then:
        - switch.toggle: power




  - platform: gpio
    name: "Temp Up"
    internal: true
    pin: 
       number: GPIO4
       mode:
         input: True
         pullup: true
    on_press:
      then:
        - switch.toggle: tmp_up

  - platform: gpio
    name: "Temp Down"
    internal: true
    pin: 
       number: GPIO12
       mode:
         input: True
         pullup: true
    on_press:
      then:
        - switch.toggle: tmp_down

  - platform: gpio
    name: "AC Mode"
    internal: true
    pin: 
       number: GPIO13
       mode:
         input: True
         pullup: true
    on_press:
      then:
        - switch.toggle: mode


switch:
  - platform: template
    name: "LG  AC Power Button"
    id: power
    turn_on_action:      
    - remote_transmitter.transmit_lg:
        data: 0x8166817E # power on/off
        nbits: 32        
  - platform: template
    name: "LG  AC Temp Up"
    id: tmp_up
    turn_on_action:      
    - remote_transmitter.transmit_lg:
        data: 0x8166A15E 
        nbits: 32 
  - platform: template
    name: "LG  AC Temp Down"
    id: tmp_down
    turn_on_action:      
    - remote_transmitter.transmit_lg:
        data: 0x816651AE
        nbits: 32 
  - platform: template
    name: "LG  AC Mode"
    id: mode
    turn_on_action:      
    - remote_transmitter.transmit_lg:
        data: 0x8166D926
        nbits: 32 
  - platform: template
    name: "LG  AC Fan Speed"
    turn_on_action:      
    - remote_transmitter.transmit_lg:
        data: 0x81669966
        nbits: 32 



